# Generated by Django 4.0.6 on 2022-07-14 00:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Areas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=55)),
            ],
        ),
        migrations.CreateModel(
            name='Motivos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=55)),
            ],
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=55)),
                ('edv', models.IntegerField()),
                ('senha', models.CharField(max_length=20)),
                ('admin', models.BooleanField()),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='areas', to='justificativas.areas')),
            ],
        ),
        migrations.CreateModel(
            name='Ocorrencias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dtInicio', models.DateField()),
                ('dtFinal', models.DateField()),
                ('hrInicio', models.TimeField(blank=True)),
                ('hrFinal', models.TimeField(blank=True)),
                ('descricao', models.TextField(blank=True)),
                ('arquivo', models.FileField(blank=True, upload_to='')),
                ('UsuarioFK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuario', to='justificativas.usuarios')),
                ('motivoFK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='motivo', to='justificativas.motivos')),
            ],
        ),
    ]
