# Generated by Django 4.0.6 on 2022-07-14 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('justificativas', '0002_usuarios_primeiroacesso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='primeiroAcesso',
            field=models.BooleanField(default=True),
        ),
    ]
